version: '3.9`'

services:

  postgres-db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=auth_finance_tracker
    ports:
      - "5433:5432"
    volumes:
      - db:/data/postgres
    networks:
      - finance_tracker
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s


  migrate:
    image: migrate/migrate
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:pass@postgres:5432/auth_finance_tracker?sslmode=disable",
      "up"
    ]
    volumes:
      - ./migrations:/migrations
    networks:
      - finance_tracker
    depends_on:
      - postgres-db

  auth:
    container_name: auth
    build: .
    depends_on:
      - postgres-db
    ports:
      - "8081:8081"
    networks:
     - finance_tracker

networks:
  finance_tracker:
    external: true
    name: finance_tracker

volumes:
  db:
